### ISSUE TITLE
老哥 ，可以交流下吗

### ISSUE THREAD

**Issue by 52ibookscn** [1181691792/TM_maotai#2]
1.你文件里的COOKIES还存在，如果是小号就无所谓了
2.软件目前就是测试demo吗？ 有可以执行抢购的代码吗？

**Comment by 1181691792** [comment]
我

**Comment by 1181691792** [comment]
> 1.你文件里的COOKIES还存在，如果是小号就无所谓了
> 2.软件当前就是测试demo吗？有可以执行抢购的代码吗？

我只是尝试一下，没事，目前这个只是一个demo，作用不大，而且这个脚本面临一个我无法解决的问题：当脚本连续请求8次，就会触发淘宝的滑动验证码

**Comment by 52ibookscn** [comment]
好的， 触发验证码这个是淘宝机制，PC端多次请求就是这样被盾掉
